### PR TITLE
Update the example

### PR DESCRIPTION
**Pull request by geoand**
* Use the latest Quarkus and LangChain4j
* Use more idiomatic Quarkus
* Use the new WebSockets Next
* Fix README

### CODE REVIEW

**Comment by LizeRaes** [comment]
Thanks a lot for this @geoand !
I have kept the main branch here as plain java as possible on purpose for general demo purposes, and I would like to keep it that way. However, I would love to have an idiomatic quarkus branch + mention this branch high up in the readme, so quarkus users can switch right away.
Would you find the time to turn this PR into 2 PRs, one for an idiomatic-quarkus branch, and one for the main branch (keep it plain java, but update quarkus version + readme)?

**Comment by geoand** [comment]
Sure thing, I can do that tomorrow

**Comment by geoand** [comment]
I will close this PR and replace it with #8 for the `main` branch

**Comment by geoand** [comment]
I have the second PR ready, but I need a branch to target :)

**Comment by LizeRaes** [comment]
Thank you so much @geoand 
There is now a branch idiomatic-quarkus that you can push to :)

**Pull request closed without merging**
